name: covid
channels:
- conda-forge
- defaults
dependencies:
    - python=3.7
    - numpy
    - scipy
    - pandas
    - matplotlib
    - nb_conda
    - jupyter
    - seaborn
    - geopandas
    - descartes
    - pip
